// <auto-generated />
namespace ClockIn_ClockOut.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class ContextUpdateBIG : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContextUpdateBIG));
        
        string IMigrationMetadata.Id
        {
            get { return "201502090323196_Context Update BIG"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
