// <auto-generated />
namespace ClockIn_ClockOut.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class ContextUpdate5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContextUpdate5));
        
        string IMigrationMetadata.Id
        {
            get { return "201502041819309_Context Update 5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
