// <auto-generated />
namespace ClockIn_ClockOut.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class contextupdate6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contextupdate6));
        
        string IMigrationMetadata.Id
        {
            get { return "201502082245588_context update 6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
